descriptor="HW1a Grader"

[defaults]
point_val = 25
print_output = true


[tests.compile]
command = "g++"
args = ["%s", "-o", "out"]
single_file = true
output_match = "error"
negate_match = true
point_val = 0


[tests.test_5]
command = "out.exe"
numeric_match = [16, 8, 4, 2, 1]


[tests.test_25]
command = "out.exe"
numeric_match = [76, 38, 19, 58, 29, 88, 44, 22, 11, 34, 17, 52, 26, 13, 40, 20, 10, 5, 16, 8, 4, 2, 1]
